<?php
include('./mainInclude/header.php');
?>

<?php
   $apiKey = "rzp_test_Z5GFsGrhvRRHrz";
?>

<!-- JQuery CDN link -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>

<form action="paymentresponse.php" method="POST">
<script
    src="https://checkout.razorpay.com/v1/checkout.js"
    data-key="rzp_test_Z5GFsGrhvRRHrz"  // Enter the Test API Key ID generated from Dashboard → Settings → API Keys
    data-amount="<?php echo $_POST['TXN_AMOUNT'] * 100;?>" // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35.
    data-currency="INR"// You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
    data-id="" // Replace with the order_id generated by you in the backend.
    data-buttontext="Pay Now"
    data-name="E-Learning"
    data-description="Payment Testing"
    data-image="" 
    data-prefill.name=""
    data-prefill.email="<?php echo $_POST['CUST_ID'] ?>"
    data-prefill.contact=""
    data-theme.color="#F37254"
></script>
<input type="hidden" custom="Hidden Element" name="hidden"/>
<input type="hidden" name="ORDER_ID" value="<?php echo $_POST['ORDER_ID'];?>"/>
<input type="hidden" name="TXN_AMOUNT" value="<?php echo $_POST['TXN_AMOUNT'];?>"/>
<input type="hidden" name="TXN_ID" value="<?php echo "TXN" . rand(10000, 99999999);?>"/>
</form>

<style>
    .razorpay-payment-button{
       margin-top: 80px;
       margin-left: 40px;
       width: 190px;
       height: 50px;
       font-weight: bold;
       font-size: 30px;
       border-radius: 10px;
       display: none;
    }
</style>

<script>
    $(document).ready(function(){
        $('.razorpay-payment-button').click();
    })
</script>

<!-- Start Footer -->
<footer class="container-fluid bg-dark text-center p-2" style="margin-top:43%;">
    <small class="text-white">Copyright &copy; 2024 || Designed By E-Learning || <a href="#login" data-bs-toggle="modal"
            data-bs-target="#adminLoginModalCenter">Admin Login</a></small>
</footer>
<!-- End Footer -->